### ISSUE TITLE
Try to write testMetadata results in 'Cannot find test [unnamed test] to add metadata'

### ISSUE THREAD

**Issue by martin-poelzl-AP** [JetBrains/TeamCity.ServiceMessages#37]
Hi!
I'm trying to write some perfomance information as service message.

At the end of my test I write:
`TestContext.WriteLine($"##teamcity[testMetadata name ='Performance' type='number' value='{elapsed}']");`
In Teamcity log I see `Cannot find test [unnamed test] to add metadata Performance/1851`

When I try to specify the name manually I get a similar error:
![image](https://github.com/JetBrains/TeamCity.ServiceMessages/assets/137481998/a5d2fe4a-ce9a-4c79-8960-3b995982b2bb)

Isn't it supposed to pick up the testname automatically when wirting while the test is running?
At least that what I understand when reading this https://www.jetbrains.com/help/teamcity/reporting-test-metadata.html#Reporting+Additional+Test+Data

My goal is to get a specific performance statistic over time about my tests.

Libraries used:
- NUnit 4.0.0
- NUnit3TestAdapter 4.5.0
- NUnit.Extension.TeamCityEventListener 1.0.9

**Comment by mchechulnikov** [comment]
@martin-poelzl-AP hi!

Please note that this TeamCity.ServiceMessages library isn't used in [NUnit.Extension.TeamCityEventListener](https://github.com/nunit/teamcity-event-listener). It's only used in [the TeamCity .NET runner](https://www.jetbrains.com/help/teamcity/net.html), which is able to run and report NUnit, xUnit, and MSTest tests as well via VSTest (`dotnet test`, `dotnet vstest` or `vstest.console.exe` on Windows).

> Isn't it supposed to pick up the testname automatically when wirting while the test is running?

Yes, you are right in general. However, you can omit `testName` attribute only in case when
1. the `testMetadata` attribute is exactly between `testStarted` and `testFininshed` service messages in a build log
2. their flow ID are equal.

For example, this sequence of service messages allows not to use `testName` attribute in `testMetadata` message
```
echo "##teamcity[testStarted name='abc']"
echo "##teamcity[testMetadata name ='point' type='number' value='42.123']"
echo "##teamcity[testFinished name='abc']"
```
However the following will produce an error
```
echo "##teamcity[testStarted name='abc']"
echo "##teamcity[testFinished name='abc']"
echo "##teamcity[testMetadata name ='point' type='number' value='42.123']"
```
You could try it by yourself with command line runner.

I'ts also important to have a proper flowId.

To make further investigation effective, could you please:
1. create [a dedicated issue in our issue tracker – YouTrack](https://www.jetbrains.com/help/teamcity/troubleshooting.html) 
2. add build configuration parameter `teamcity.build.serviceMessages.logOriginal` with value `true` to the build and run it
4. share the build log with us via the created issue on YouTrack.

It allows us to see the sequence of service messages in your build log and gives a possibility to reproduce the situation.

----
Since the issue is not related to the TeamCity.ServiceMessages library, I'm going to close the current issue. We'll meet at the issue tracker!
